### ISSUE TITLE
Scheduler erlang node needs more unique name

### ISSUE THREAD

**Issue by sanmiguel** [basho-labs/riak-mesos-scheduler#60]
If you run multiple (differently named) instances of RMF, and Mesos places 2 or more on the same agent, only the first will run because they are all given the nodename 'riak_mesos@127.0.0.1'. More sensible might be to call it something derived from the framework name.

**Comment by mokele** [comment]
Are there any services that are currently hardcoded to talk to `riak_mesos@127.0.0.1` or is it simple enough to just change to be derived from the framework name and that's it?

**Comment by sanmiguel** [comment]
We had no functionality that required the scheduler or the executor to run in distributed mode under normal operation, so we simply no longer set a node name. No nodename, no distribution, no name clashes.
