### ISSUE TITLE
removing unschedulable node results in stuck status "shutting_down"

### ISSUE THREAD

**Issue by seanjensengrey** [basho-labs/riak-mesos-scheduler#66]
# repro

1. create more nodes than capacity
2. remove unschedulable node, `riak-mesos node --cluster weatherstation remove --node riak-weatherstation-10`

# result

Node remains in cluster list

`riak-mesos node --cluster weatherstation list | jq .`
```json
{
  "nodes": [
    "riak-weatherstation-3",
    "riak-weatherstation-10",
    "riak-weatherstation-7",
    "riak-weatherstation-9",
    "riak-weatherstation-6",
    "riak-weatherstation-8",
    "riak-weatherstation-1",
    "riak-weatherstation-2"
  ]
}
```

Node status remains fixed 

`riak-mesos node --cluster weatherstation info --node riak-weatherstation-10 | jq .`
```json
{
  "riak-weatherstation-10": {
    "key": "riak-weatherstation-10",
    "status": "shutting_down",
    "location": {
      "node_name": "",
      "hostname": "",
      "http_port": "undefined",
      "pb_port": "undefined",
      "disterl_port": "undefined",
      "agent_id_value": ""
    },
    "container_path": "",
    "persistence_id": ""
  }
}
```

# expected

Node is removed.

**Comment by seanjensengrey** [comment]
Confirmed with scheduler-1.1.1, output of `riak-mesos framework status` https://gist.github.com/5ebf0b01693d939570cb17838f19b947

**Comment by sanmiguel** [comment]
Thanks for the reproductions teps @seanjensengrey - can reliably reproduce this here, will investigate the cause.

In the meantime, if you hit it again you can do 

```
riak-mesos node remove --force --node $offending_node
```

 for any node stuck in `shutting_down`: it will immediately remove it from the scheduler.
